name: "push"
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version:
          - 18.x
          - 20.x
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Ensure line endings are consistent
        run: git config --global core.autocrlf input
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            .rdf-test-suite-cache
            .rdf-test-suite-ldf-cache
          key: ${{ runner.os }}-test-modules-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Build project
        run: yarn run build
      - name: Run depcheck
        run: yarn run depcheck
      - name: Run browser-tests
        run: yarn run test-browser
      - name: Run tests
        run: yarn run test-ci
      - name: Submit coverage results
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.node-version }}
          parallel: true

  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Consolidate test coverage from different jobs
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-lint-modules-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Run linter
        run: yarn run lint
  docs:
    needs:
      - test
      - lint
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-docs-modules-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Build docs
        run: yarn run doc
      - name: Deploy TSDoc to GitHub Pages
        if: startsWith(github.ref, 'refs/heads/master')
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: documentation
          clean: true
